name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version: [7.4, '8.0', 8.1]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: openssl
          tools: composer:v2
          coverage: xdebug2
      - name: install dependencies
        run: composer install
      - name: unit tests
        env:
          OPENSSL_VERSION: 1.1.1
        run: composer run phpunit